### ISSUE TITLE
Add the "xxh" and "xxh-shell" topics to the repo

### ISSUE THREAD

**Issue by anki-code** [krageon/xxh-shell-elvish#1]
Hi! subj :)

**Comment by krageon** [comment]
Hi! I'm way too drunk to know what this means right now but I will look at it when sober and fix it :)

**Comment by anki-code** [comment]
Ha-ha, click here (right icon):
![image](https://user-images.githubusercontent.com/1708680/145457992-5a0d4b66-c3fd-47a3-8e95-44a51fa66054.png)

and add topics :)

**Comment by krageon** [comment]
Oh that was super helpful. I think I did it! Thank you :)

**Comment by anki-code** [comment]
Great work man! :)

**Comment by krageon** [comment]
Have a nice day!
